import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  AlertTriangle, BarChart3, CheckCircle2, ClipboardList, Copy, Eye, FileDown,
  Headphones, LayoutDashboard, LogOut, Phone, PhoneCall, Plus, RefreshCw, Search,
  Settings, ShieldBan, Target, Upload, Users, Wand2, X
} from 'lucide-react';
import { api, token } from './services/api';
import './style.css';

const APP_NAME = 'ReferencIA Discador';
const DEFAULT_LOGIN = 'admin@score.com.br';
const DEFAULT_PASSWORD = 'Admin@123456';
const statuses = ['NOVO','EM_FILA','LIGANDO','ATENDIDO','NAO_ATENDEU','OCUPADO','RETORNO','INTERESSADO','SEM_INTERESSE','MATRICULADO','NAO_LIGAR_NOVAMENTE','ERRO_CHAMADA'];
const dispositions = ['ATENDIDO','NAO_ATENDEU','INTERESSADO','SEM_INTERESSE','MATRICULADO','RETORNO','OCUPADO','CAIXA_POSTAL','NUMERO_INVALIDO','NAO_LIGAR_NOVAMENTE'];
const menu = [
  ['Dashboard', LayoutDashboard], ['Campanhas', Target], ['Importar Leads', Upload], ['Leads', Phone],
  ['Mesa do Operador', Headphones], ['Relatórios', BarChart3], ['Não Ligar', ShieldBan], ['Usuários', Users], ['VoIP', Settings]
] as const;

type Msg = { type: 'ok'|'err'|'info'; text: string } | null;
type MenuAction = { label: string; icon?: React.ReactNode; action: () => void; danger?: boolean };

function fmt(v:any){ if(v===null||v===undefined||v==='')return '—'; if(typeof v==='number')return v.toLocaleString('pt-BR',{maximumFractionDigits:2}); if(typeof v==='boolean')return v?'Sim':'Não'; if(typeof v==='object')return '—'; if(String(v).includes('T'))return String(v).replace('T',' ').slice(0,16); return String(v).replaceAll('_',' '); }
function downloadCsv(name:string, rows:any[]){ const csv=[Object.keys(rows[0]||{}).join(';'),...rows.map(r=>Object.values(r).map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';'))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); a.download=name; a.click(); }
function useLoad<T>(loader:()=>Promise<T>, deps:React.DependencyList=[]){ const [data,setData]=useState<T|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''); async function reload(){try{setLoading(true);setError('');setData(await loader())}catch(e:any){setError(e.message||'Falha ao carregar')}finally{setLoading(false)}} useEffect(()=>{reload()},deps); return {data,loading,error,reload,setData}; }
function Notice({msg}:{msg:Msg}){ if(!msg)return null; return <div className={`notice ${msg.type}`}>{msg.type==='err'?<AlertTriangle size={18}/>:<CheckCircle2 size={18}/>}<span>{msg.text}</span></div>; }
function Empty({text}:{text:string}){return <div className="empty"><ClipboardList size={36}/><strong>Nenhum registro encontrado</strong><span>{text}</span></div>}
function ContextMenu({x,y,items,onClose}:{x:number;y:number;items:MenuAction[];onClose:()=>void}){ useEffect(()=>{const f=()=>onClose(); window.addEventListener('click',f); window.addEventListener('scroll',f); return()=>{window.removeEventListener('click',f); window.removeEventListener('scroll',f)}},[]); return <div className="contextMenu" style={{left:x,top:y}} onClick={e=>e.stopPropagation()}>{items.map((it,i)=><button key={i} className={it.danger?'danger':''} onClick={()=>{it.action();onClose()}}>{it.icon}{it.label}</button>)}</div> }

function DataTable({rows,columns,onRowMenu}:{rows:any[];columns:{key:string;label:string}[];onRowMenu?:(row:any)=>MenuAction[]}){
  const [ctx,setCtx]=useState<{x:number;y:number;items:MenuAction[]}|null>(null);
  if(!rows?.length)return <Empty text="Crie, importe ou filtre dados para visualizar aqui."/>;
  return <div className="tableWrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} onContextMenu={e=>{if(onRowMenu){e.preventDefault();setCtx({x:e.clientX,y:e.clientY,items:onRowMenu(r)})}}}>{columns.map(c=><td key={c.key}>{fmt(r[c.key])}</td>)}</tr>)}</tbody></table>{ctx&&<ContextMenu {...ctx} onClose={()=>setCtx(null)}/>}</div>;
}

function Login({on}:{on:()=>void}){ const [email,setEmail]=useState(DEFAULT_LOGIN),[password,setPassword]=useState(DEFAULT_PASSWORD),[msg,setMsg]=useState<Msg>(null),[loading,setLoading]=useState(false); async function submit(e:React.FormEvent){e.preventDefault();try{setLoading(true);const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',d.token);on()}catch(x:any){setMsg({type:'err',text:x.message||'Não foi possível entrar'})}finally{setLoading(false)}} return <main className="loginPage"><section className="loginHero"><div className="brandMark">IA</div><h1>{APP_NAME}</h1><p>Central de campanhas, listas, fila de ligação, desfechos, produtividade e compliance para operação ativa.</p><div className="heroBullets"><span>Campanhas</span><span>Discagem</span><span>Contexto rápido</span><span>LGPD</span></div></section><form onSubmit={submit} className="loginCard"><small>Acesso restrito</small><h2>Entrar na operação</h2><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><Notice msg={msg}/><button disabled={loading}>{loading?'Entrando...':'Entrar'}</button><p className="muted">Use apenas credenciais autorizadas. Todas as ações relevantes devem ser auditáveis.</p></form></main> }
function Shell({children,page,setPage}:{children:React.ReactNode;page:string;setPage:(p:string)=>void}){return <div className="appShell"><aside className="sidebar"><div className="logo"><span>Referenc</span><b>IA</b><small>Discador comercial</small></div><nav>{menu.map(([m,I])=><button key={m} className={page===m?'active':''} onClick={()=>setPage(m)}><I size={18}/>{m}</button>)}</nav><button className="logout" onClick={()=>{localStorage.clear();location.reload()}}><LogOut size={18}/>Sair</button></aside><main className="content"><header className="topbar"><div><small>Operação ativa</small><h1>{page}</h1></div><div className="statusPill"><span/> API conectada</div></header>{children}</main></div>}

function Dashboard({setPage}:{setPage:(p:string)=>void}){ const {data,loading,error,reload}=useLoad<any>(()=>api('/dashboard/summary'),[]); const cards=[['Total de leads',data?.total,'Base disponível'],['Novos',data?.newLeads,'Aguardando ação'],['Chamadas hoje',data?.callsToday,'Tentativas registradas'],['Atendidos',data?.atendidos,'Contatos humanos'],['Interessados',data?.interessados,'Potencial comercial'],['Matrículas',data?.matriculas,'Conversão final'],['Não ligar',data?.blocked,'Bloqueios LGPD'],['Conversão',`${fmt((data?.taxaConversao||0)*100)}%`,'Matrículas / leads']]; return <><div className="heroPanel"><div><small>Visão geral</small><h2>Operação de discagem com fluxo de ponta a ponta</h2><p>Baseado em padrões de contact center: campanha, fila, discagem, screen pop, desfecho, bloqueio e relatórios.</p></div><button onClick={reload}><RefreshCw size={17}/>Atualizar</button></div><div className="pipeline"><div>Base importada</div><div>Fila ativa</div><div>Ligação</div><div>Desfecho</div><div>Relatório</div></div>{error&&<Notice msg={{type:'err',text:error}}/>}<div className="kpiGrid">{cards.map(([a,b,c])=><div className="kpi" key={a}><small>{a}</small><strong>{loading?'...':fmt(b)}</strong><span>{c}</span></div>)}</div><section className="twoCols"><div className="panel"><h3>Atalhos operacionais</h3><div className="steps"><button onClick={()=>setPage('Campanhas')}>1. Criar campanha</button><button onClick={()=>setPage('Importar Leads')}>2. Importar leads</button><button onClick={()=>setPage('Mesa do Operador')}>3. Operar fila</button><button onClick={()=>setPage('Relatórios')}>4. Medir resultado</button></div></div><div className="panel accent"><h3>Menu de contexto</h3><p>Clique com o botão direito nas tabelas de leads, campanhas e relatórios para ações rápidas, inspirado no conceito de menus por contexto usados em sistemas com centenas de registros.</p></div></section></> }

function Campaigns(){ const {data,loading,error,reload}=useLoad<any[]>(()=>api('/campaigns'),[]); const [form,setForm]=useState<any>({name:'',description:'',status:'ATIVA',maxAttemptsPerLead:3,minIntervalMinutes:60}); const [msg,setMsg]=useState<Msg>(null); async function save(e:React.FormEvent){e.preventDefault();try{await api('/campaigns',{method:'POST',body:JSON.stringify({...form,maxAttemptsPerLead:Number(form.maxAttemptsPerLead),minIntervalMinutes:Number(form.minIntervalMinutes)})});setForm({name:'',description:'',status:'ATIVA',maxAttemptsPerLead:3,minIntervalMinutes:60});setMsg({type:'ok',text:'Campanha criada com sucesso.'});reload()}catch(e:any){setMsg({type:'err',text:e.message})}} const menu=(r:any)=>[{label:'Copiar nome',icon:<Copy size={15}/>,action:()=>navigator.clipboard.writeText(r.name||'')},{label:'Atualizar lista',icon:<RefreshCw size={15}/>,action:reload},{label:'Ir para importar leads',icon:<Upload size={15}/>,action:()=>alert('Abra Importar Leads e selecione esta campanha.')}]; return <section className="pageGrid"><div className="panel"><h3>Nova campanha</h3><p className="muted">Crie uma operação por base, canal, curso, consultor ou período.</p><form className="formGrid" onSubmit={save}><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Vestibular Julho - Unidade Centro"/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ATIVA</option><option>RASCUNHO</option><option>PAUSADA</option><option>ENCERRADA</option></select></label><label>Tentativas por lead<input type="number" value={form.maxAttemptsPerLead} onChange={e=>setForm({...form,maxAttemptsPerLead:e.target.value})}/></label><label>Intervalo mínimo min.<input type="number" value={form.minIntervalMinutes} onChange={e=>setForm({...form,minIntervalMinutes:e.target.value})}/></label><label className="wide">Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Objetivo, público, origem, regra de acionamento e observações da campanha"/></label><button><Plus size={17}/>Criar campanha</button></form><Notice msg={msg}/></div><div className="panel listPanel"><h3>Campanhas cadastradas</h3>{error&&<Notice msg={{type:'err',text:error}}/>}{loading?<p>Carregando...</p>:<DataTable rows={data||[]} onRowMenu={menu} columns={[{key:'name',label:'Campanha'},{key:'status',label:'Status'},{key:'allowedCallStart',label:'Início'},{key:'allowedCallEnd',label:'Fim'},{key:'maxAttemptsPerLead',label:'Tent.'}]}/>}</div></section> }

function ImportLeads(){ const {data:camps,reload}=useLoad<any[]>(()=>api('/campaigns'),[]); const [campaignId,setCampaignId]=useState(''),[msg,setMsg]=useState<Msg>(null); useEffect(()=>{if(!campaignId&&camps?.[0]?.id)setCampaignId(camps[0].id)},[camps]); async function up(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]; if(!f||!campaignId)return; const fd=new FormData();fd.append('file',f);try{const r=await fetch(`/api/imports/${campaignId}/upload`,{method:'POST',headers:{Authorization:`Bearer ${token()}`},body:fd});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erro ao importar');setMsg({type:'ok',text:`Importação: ${d.totalImported} importados, ${d.duplicates} duplicados, ${d.invalid} inválidos, ${d.blocked} bloqueados.`})}catch(x:any){setMsg({type:'err',text:x.message})}} return <section className="twoCols"><div className="panel"><h3>Importar base de leads</h3><p className="muted">Aceita CSV/XLSX. A campanha controla regras de tentativas, horários e relatórios.</p><label>Campanha<select value={campaignId} onChange={e=>setCampaignId(e.target.value)}>{(camps||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="uploadBox"><Upload size={30}/><span>Selecionar arquivo CSV/XLSX</span><input type="file" accept=".csv,.xlsx" onChange={up}/></label><Notice msg={msg}/><button onClick={reload}><RefreshCw size={17}/>Atualizar campanhas</button></div><div className="panel"><h3>Modelo de colunas</h3><div className="tags">{['nome','telefone','cpf','email','curso','origem','observacao'].map(x=><span key={x}>{x}</span>)}</div><p className="muted">O telefone é obrigatório. O sistema deduplica por telefone dentro da campanha e respeita bloqueios da lista “Não Ligar”.</p><div className="miniGuide"><b>Antes de importar</b><span>Confirme origem e finalidade da base.</span><span>Remova contatos sem autorização.</span><span>Use campanhas separadas por curso/unidade.</span></div></div></section> }

function Leads(){ const [q,setQ]=useState<any>({status:'',nome:'',telefone:''}),[rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState<Msg>(null); async function load(){const params=new URLSearchParams();Object.entries(q).forEach(([k,v]:any)=>{if(v)params.set(k,v)});try{setRows(await api(`/leads?${params.toString()}`))}catch(e:any){setMsg({type:'err',text:e.message})}} useEffect(()=>{load()},[]); async function updateLead(row:any,status:string){try{await api(`/leads/${row.id}`,{method:'PATCH',body:JSON.stringify({status})});setMsg({type:'ok',text:`Lead marcado como ${status.replaceAll('_',' ')}`});load()}catch(e:any){setMsg({type:'err',text:e.message})}} const menu=(r:any)=>[{label:'Ver detalhes',icon:<Eye size={15}/>,action:()=>alert(JSON.stringify(r,null,2))},{label:'Copiar telefone',icon:<Copy size={15}/>,action:()=>navigator.clipboard.writeText(r.phoneNormalized||'')},{label:'Marcar interessado',icon:<CheckCircle2 size={15}/>,action:()=>updateLead(r,'INTERESSADO')},{label:'Marcar matrícula',icon:<Target size={15}/>,action:()=>updateLead(r,'MATRICULADO')},{label:'Não ligar novamente',icon:<ShieldBan size={15}/>,danger:true,action:()=>updateLead(r,'NAO_LIGAR_NOVAMENTE')}]; return <><section className="panel"><h3>Buscar leads</h3><div className="filters"><label>Status<select value={q.status} onChange={e=>setQ({...q,status:e.target.value})}><option value="">Todos</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Nome<input value={q.nome} onChange={e=>setQ({...q,nome:e.target.value})}/></label><label>Telefone<input value={q.telefone} onChange={e=>setQ({...q,telefone:e.target.value})}/></label><button onClick={load}><Search size={17}/>Filtrar</button></div><Notice msg={msg}/></section><div className="mt"><DataTable rows={rows} onRowMenu={menu} columns={[{key:'name',label:'Nome'},{key:'phoneNormalized',label:'Telefone'},{key:'course',label:'Curso'},{key:'origin',label:'Origem'},{key:'status',label:'Status'},{key:'attemptsCount',label:'Tent.'}]}/></div></> }

function Operator(){ const [queue,setQueue]=useState<any[]>([]),[lead,setLead]=useState<any>(),[call,setCall]=useState<any>(),[notes,setNotes]=useState(''),[msg,setMsg]=useState<Msg>(null); async function load(){const r=await api('/leads?status=EM_FILA');setQueue(r);setLead(r[0])} useEffect(()=>{load().catch(()=>{})},[]); async function start(){if(!lead)return;try{setCall(await api('/calls/start',{method:'POST',body:JSON.stringify({leadId:lead.id})}));setMsg({type:'ok',text:'Chamada iniciada no provedor mock.'})}catch(e:any){setMsg({type:'err',text:e.message})}} async function finish(s:string){if(!call)return;try{await api(`/calls/${call.id}/finish`,{method:'POST',body:JSON.stringify({finalDisposition:s,notes,doNotCall:s==='NAO_LIGAR_NOVAMENTE'})});setMsg({type:'ok',text:`Desfecho salvo: ${s.replaceAll('_',' ')}`});setCall(undefined);setNotes('');load()}catch(e:any){setMsg({type:'err',text:e.message})}} return <section className="operatorLayout"><div className="panel leadCard"><h3>Screen pop do lead</h3><p className="muted">Dados principais aparecem antes da ligação para reduzir tempo de atendimento.</p><Notice msg={msg}/>{lead?<><div className="person"><small>Lead em fila</small><h2>{lead.name}</h2><p>{lead.phoneNormalized}</p><span>{lead.course||'Curso não informado'} • {lead.origin||'Origem não informada'}</span></div><div className="callActions"><button className="callBtn" onClick={start}><PhoneCall size={20}/>{call?'Chamada iniciada':'Iniciar ligação'}</button><textarea placeholder="Observação do atendimento" value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="dispositions">{dispositions.map(s=><button key={s} disabled={!call} onClick={()=>finish(s)}>{s.replaceAll('_',' ')}</button>)}</div></>:<Empty text="Nenhum lead em fila."/>}</div><div className="panel"><h3>Próximos da fila</h3>{queue.slice(0,10).map((l,i)=><button className="queueItem" key={l.id} onClick={()=>setLead(l)}>{i+1}. {l.name}<span>{l.phoneNormalized}</span></button>)}</div></section> }

function Reports(){ const {data,loading,error,reload}=useLoad<any[]>(()=>api('/reports/calls'),[]); const rows=data||[]; const menu=(r:any)=>[{label:'Copiar telefone',icon:<Copy size={15}/>,action:()=>navigator.clipboard.writeText(r.lead?.phoneNormalized||'')},{label:'Ver JSON',icon:<Eye size={15}/>,action:()=>alert(JSON.stringify(r,null,2))}]; return <><div className="heroPanel"><div><small>Relatórios</small><h2>Auditoria e resultado da operação</h2><p>Veja chamadas, operador, campanha, lead, duração, desfecho e exporte CSV para gestão.</p></div><button onClick={()=>downloadCsv('referencia-discador-relatorio.csv',rows)}><FileDown size={17}/>Exportar CSV</button></div>{error&&<Notice msg={{type:'err',text:error}}/>}{loading?<p>Carregando...</p>:<DataTable rows={rows.map(r=>({id:r.id,campanha:r.campaign?.name,operador:r.operator?.name,lead:r.lead?.name,telefone:r.lead?.phoneNormalized,status:r.status,desfecho:r.finalDisposition,criado:r.createdAt}))} onRowMenu={menu} columns={[{key:'campanha',label:'Campanha'},{key:'operador',label:'Operador'},{key:'lead',label:'Lead'},{key:'telefone',label:'Telefone'},{key:'status',label:'Status'},{key:'desfecho',label:'Desfecho'},{key:'criado',label:'Data'}]}/>}</> }

function DoNotCall(){ const {data,loading,error}=useLoad<any[]>(()=>api('/do-not-call'),[]); return <><div className="panel accent"><h3>Lista Não Ligar</h3><p>Bloqueie e audite contatos que solicitaram interrupção, mantendo conformidade operacional e LGPD.</p></div><div className="mt">{error&&<Notice msg={{type:'err',text:error}}/>}{loading?<p>Carregando...</p>:<DataTable rows={data||[]} columns={[{key:'phoneNormalized',label:'Telefone'},{key:'reason',label:'Motivo'},{key:'blockedAt',label:'Bloqueado em'}]}/>}</div></> }
function UsersPage(){ const {data,loading,error,reload}=useLoad<any[]>(()=>api('/users'),[]); const [form,setForm]=useState<any>({name:'',email:'',password:'',role:'OPERADOR',extension:''}),[msg,setMsg]=useState<Msg>(null); async function save(e:React.FormEvent){e.preventDefault();try{await api('/users',{method:'POST',body:JSON.stringify(form)});setMsg({type:'ok',text:'Usuário criado.'});setForm({name:'',email:'',password:'',role:'OPERADOR',extension:''});reload()}catch(e:any){setMsg({type:'err',text:e.message})}} return <section className="pageGrid"><div className="panel"><h3>Novo usuário</h3><form className="formGrid" onSubmit={save}><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Senha<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Perfil<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>ADMIN</option><option>SUPERVISOR</option><option>OPERADOR</option></select></label><label>Ramal<input value={form.extension} onChange={e=>setForm({...form,extension:e.target.value})}/></label><button><Plus size={17}/>Criar</button></form><Notice msg={msg}/></div><div className="panel listPanel"><h3>Equipe</h3>{error&&<Notice msg={{type:'err',text:error}}/>}{loading?<p>Carregando...</p>:<DataTable rows={data||[]} columns={[{key:'name',label:'Nome'},{key:'email',label:'Email'},{key:'role',label:'Perfil'},{key:'extension',label:'Ramal'},{key:'active',label:'Ativo'}]}/>}</div></section> }
function Voip(){ const {data}=useLoad<any>(()=>api('/voip/config'),[]); return <section className="twoCols"><div className="panel"><h3>Configuração VoIP</h3><p className="muted">Atualmente o provedor está em modo mock. Use esta tela como checklist para futura integração SIP/Asterisk/PABX.</p><DataTable rows={[data||{}]} columns={[{key:'provider',label:'Provider'},{key:'asteriskHost',label:'Host'},{key:'asteriskPort',label:'Porta'},{key:'asteriskContext',label:'Contexto'}]}/></div><div className="panel accent"><h3>Próximas integrações</h3><div className="miniGuide"><span>Discagem automática com controle de canais.</span><span>Screen pop no atendimento humano.</span><span>Gravação e auditoria por chamada.</span><span>Roteamento por consultor, curso ou unidade.</span></div></div></section> }

function App(){ const [ok,setOk]=useState(!!localStorage.getItem('token')); const [page,setPage]=useState<string>('Dashboard'); const content=useMemo(()=> page==='Dashboard'?<Dashboard setPage={setPage}/>:page==='Campanhas'?<Campaigns/>:page==='Importar Leads'?<ImportLeads/>:page==='Leads'?<Leads/>:page==='Mesa do Operador'?<Operator/>:page==='Relatórios'?<Reports/>:page==='Não Ligar'?<DoNotCall/>:page==='Usuários'?<UsersPage/>:<Voip/>,[page]); if(!ok)return <Login on={()=>setOk(true)}/>; return <Shell page={page} setPage={setPage}>{content}</Shell>; }

createRoot(document.getElementById('root')!).render(<App/>);
