import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Phone,LayoutDashboard,Upload,Users,FileBarChart,ShieldBan,Settings,Headphones,Target}from'lucide-react';import{api}from'./services/api';import'./style.css';
const menu=[['Dashboard',LayoutDashboard],['Campanhas',Target],['Importar Leads',Upload],['Leads',Phone],['Operador',Headphones],['Relatórios',FileBarChart],['Lista Não Ligar',ShieldBan],['Usuários',Users],['Configurações VoIP',Settings]] as const;
function Login({on}:{on:()=>void}){const[email,setEmail]=useState('admin@score.com.br'),[password,setPassword]=useState('Score@123'),[err,setErr]=useState('');async function submit(e:any){e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',d.token);on()}catch(x:any){setErr(x.message)}}return <main className="login"><form onSubmit={submit} className="panel"><h1>SCORE Discador</h1><p>Gestão de campanhas, ligações e resultados comerciais.</p><input value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<b className="err">{err}</b>}<button>Entrar</button></form></main>}
function Table({rows}:{rows:any[]}){return <div className="table"><table><tbody>{rows.slice(0,12).map((r,i)=><tr key={i}>{Object.values(r).slice(0,6).map((v:any,j)=><td key={j}>{typeof v==='object'?'—':String(v??'')}</td>)}</tr>)}</tbody></table></div>}
function Dashboard(){const[d,setD]=useState<any>({});useEffect(()=>{api('/dashboard/summary').then(setD)},[]);return <><h2>Dashboard</h2><div className="grid">{Object.entries(d).map(([k,v])=><div className="card" key={k}><small>{k}</small><strong>{typeof v==='number'?Number(v).toLocaleString('pt-BR',{maximumFractionDigits:2}):String(v)}</strong></div>)}</div><section className="panel"><h3>Operação controlada</h3><p>Use os dados apenas para finalidade autorizada. Registre corretamente o resultado do atendimento.</p></section></>}
function Campaigns(){const[rows,setRows]=useState<any[]>([]),[name,setName]=useState('');useEffect(()=>{api('/campaigns').then(setRows)},[]);async function add(){await api('/campaigns',{method:'POST',body:JSON.stringify({name:name||'Nova campanha',status:'ATIVA'})});setRows(await api('/campaigns'))}return <><h2>Campanhas</h2><div className="actions"><input placeholder="Nome da campanha" onChange={e=>setName(e.target.value)}/><button onClick={add}>Criar</button></div><Table rows={rows}/></>}
function Import(){const[camps,setCamps]=useState<any[]>([]),[campaignId,setC]=useState(''),[msg,setMsg]=useState('');useEffect(()=>{api('/campaigns').then((x)=>{setCamps(x);setC(x[0]?.id)})},[]);async function up(e:any){const f=e.target.files[0],fd=new FormData();fd.append('file',f);const r=await fetch((import.meta.env.VITE_API_URL||'http://localhost:4000/api')+`/imports/${campaignId}/upload`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('token')}`},body:fd});setMsg(JSON.stringify(await r.json()))}return <><h2>Importar Leads</h2><div className="panel"><select onChange={e=>setC(e.target.value)}>{camps.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="file" accept=".csv,.xlsx" onChange={up}/><pre>{msg}</pre></div></>}
function Leads(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api('/leads').then(setRows)},[]);return <><h2>Leads</h2><Table rows={rows}/></>}
function Operator(){const[lead,setLead]=useState<any>(),[call,setCall]=useState<any>(),[notes,setNotes]=useState('');useEffect(()=>{api('/leads?status=EM_FILA').then((r)=>setLead(r[0]))},[]);async function start(){setCall(await api('/calls/start',{method:'POST',body:JSON.stringify({leadId:lead.id})}))}async function finish(s:string){await api(`/calls/${call.id}/finish`,{method:'POST',body:JSON.stringify({finalDisposition:s,notes,doNotCall:s==='NAO_LIGAR_NOVAMENTE'})});alert('Resultado salvo')}return <><h2>Operador</h2><div className="panel operator"><p className="warn">Use os dados apenas para finalidade autorizada.</p>{lead?<><h3>{lead.name}</h3><p>{lead.phoneNormalized} • {lead.course} • {lead.origin}</p><button className="call" onClick={start}>Ligar</button><textarea placeholder="Observação" onChange={e=>setNotes(e.target.value)}/><div className="chips">{['ATENDIDO','NAO_ATENDEU','INTERESSADO','SEM_INTERESSE','MATRICULADO','RETORNO','NAO_LIGAR_NOVAMENTE'].map(s=><button key={s} disabled={!call} onClick={()=>finish(s)}>{s}</button>)}</div></>:<p>Nenhum lead em fila.</p>}</div></>}
function Generic({title,path}:{title:string,path:string}){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api(path).then(setRows).catch(()=>setRows([]))},[path]);return <><h2>{title}</h2><Table rows={rows}/></>}
function App(){const[ok,setOk]=useState(!!localStorage.getItem('token')), [page,setPage]=useState('Dashboard'); if(!ok)return <Login on={()=>setOk(true)}/>; const content=page==='Dashboard'?<Dashboard/>:page==='Campanhas'?<Campaigns/>:page==='Importar Leads'?<Import/>:page==='Leads'?<Leads/>:page==='Operador'?<Operator/>:page==='Relatórios'?<Generic title="Relatórios" path="/reports/calls"/>:page==='Lista Não Ligar'?<Generic title="Lista Não Ligar" path="/do-not-call"/>:page==='Usuários'?<Generic title="Usuários" path="/users"/>:<Generic title="Configurações VoIP" path="/voip/config"/>;return <div className="app"><aside><h1>SCORE<br/><span>Discador</span></h1>{menu.map(([m,I])=><button key={m} className={page===m?'active':''} onClick={()=>setPage(m)}><I size={18}/>{m}</button>)}<button onClick={()=>{localStorage.clear();location.reload()}}>Sair</button></aside><main>{content}</main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
