import { Router } from 'express'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import multer from 'multer'; import xlsx from 'xlsx'; import fs from 'node:fs'; import csv from 'csv-parser';
import { prisma } from '../prisma.js'; import { auth, permit } from '../middlewares/auth.js'; import { audit } from '../services/audit.js'; import { getVoipService } from '../services/voip.js'; import { isValidBrazilPhone, normalizeBrazilPhone } from '../utils/phone.js'; import { campaignSchema, finishCallSchema, loginSchema, userSchema } from '../schemas.js';
const r=Router(); const upload=multer({dest:'uploads/'}); const sign=(u:any)=>jwt.sign({id:u.id,email:u.email,role:u.role},process.env.JWT_SECRET||'dev',{expiresIn:'8h'});
const cleanKey=(v:any)=>String(v??'').replace(/^\uFEFF/,'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const aliases:Record<string,string[]>={nome:['nome','name','aluno','lead','cliente'],telefone:['telefone','phone','celular','whatsapp','numero','número','fone'],cpf:['cpf','documento'],email:['email','e_mail','mail'],curso:['curso','course'],origem:['origem','source'],observacao:['observacao','observacao_','obs','observação','notes']};
function normalizeRow(row:any){const out:any={}; for(const [rawKey,value] of Object.entries(row||{})){const key=cleanKey(rawKey); const target=Object.entries(aliases).find(([,keys])=>keys.map(cleanKey).includes(key))?.[0]||key; out[target]=typeof value==='string'?value.trim():value;} return out;}
function scoreRows(rows:any[]){let score=0; for(const row of rows.slice(0,25)){const n=normalizeRow(row); if(n.telefone) score+=4; if(n.nome) score+=2; if(n.email) score+=1; if(n.curso) score+=1;} return score;}
function detectDelimiter(filePath:string){const sample=fs.readFileSync(filePath,'utf8').slice(0,4096); const firstLine=(sample.split(/\r?\n/).find(Boolean)||''); const semi=(firstLine.match(/;/g)||[]).length; const comma=(firstLine.match(/,/g)||[]).length; const tab=(firstLine.match(/\t/g)||[]).length; if(semi>=comma&&semi>=tab&&semi>0)return ';'; if(tab>=comma&&tab>0)return '\t'; return ',';}
async function rowsFrom(file:any){ if(file.originalname.toLowerCase().endsWith('.xlsx')){const wb=xlsx.readFile(file.path,{cellDates:false}); let best:any[]=[]; let bestScore=-1; for(const sheetName of wb.SheetNames){const rows=xlsx.utils.sheet_to_json(wb.Sheets[sheetName],{defval:'',raw:false}) as any[]; const s=scoreRows(rows); if(s>bestScore){best=rows; bestScore=s;}} return best.map(normalizeRow);} const rows:any[]=[]; const separator=detectDelimiter(file.path); await new Promise((ok,er)=>fs.createReadStream(file.path).pipe(csv({separator,mapHeaders:({header})=>cleanKey(header)})).on('data',d=>rows.push(normalizeRow(d))).on('end',ok).on('error',er)); return rows; }
r.post('/auth/login',async(req,res)=>{const b=loginSchema.parse(req.body); const u=await prisma.user.findUnique({where:{email:b.email}}); if(!u||!await bcrypt.compare(b.password,u.passwordHash)) return res.status(401).json({message:'Credenciais inválidas'}); await audit(u.id,'LOGIN','User',u.id); res.json({token:sign(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,extension:u.extension}})});
r.get('/auth/me',auth,async(req,res)=>res.json(await prisma.user.findUnique({where:{id:req.user!.id},select:{id:true,name:true,email:true,role:true,extension:true}})));
r.get('/users',auth,permit('ADMIN','SUPERVISOR'),async(_,res)=>res.json(await prisma.user.findMany({select:{id:true,name:true,email:true,role:true,extension:true,active:true,createdAt:true}})));
r.post('/users',auth,permit('ADMIN'),async(req,res)=>{const b=userSchema.required({password:true}).parse(req.body); const u=await prisma.user.create({data:{name:b.name,email:b.email,role:b.role,extension:b.extension,passwordHash:await bcrypt.hash(b.password!,10)}}); await audit(req.user!.id,'USER_CREATED','User',u.id); res.status(201).json(u)});
r.patch('/users/:id',auth,permit('ADMIN'),async(req,res)=>{const b=userSchema.partial().parse(req.body); const data:any={...b}; if(b.password){data.passwordHash=await bcrypt.hash(b.password,10); delete data.password} const u=await prisma.user.update({where:{id:req.params.id},data}); res.json(u)});
r.delete('/users/:id',auth,permit('ADMIN'),async(req,res)=>res.json(await prisma.user.update({where:{id:req.params.id},data:{active:false}})));
r.get('/campaigns',auth,async(_,res)=>res.json(await prisma.campaign.findMany({include:{responsible:true,_count:{select:{leads:true,calls:true}}},orderBy:{createdAt:'desc'}})));
r.post('/campaigns',auth,permit('ADMIN'),async(req,res)=>{const c=await prisma.campaign.create({data:campaignSchema.parse(req.body) as any}); await audit(req.user!.id,'CAMPAIGN_CREATED','Campaign',c.id); res.status(201).json(c)});
r.get('/campaigns/:id',auth,async(req,res)=>res.json(await prisma.campaign.findUnique({where:{id:req.params.id},include:{leads:true}})));
r.patch('/campaigns/:id',auth,permit('ADMIN','SUPERVISOR'),async(req,res)=>{const c=await prisma.campaign.update({where:{id:req.params.id},data:campaignSchema.partial().parse(req.body) as any}); await audit(req.user!.id,'CAMPAIGN_UPDATED','Campaign',c.id); res.json(c)});
r.post('/imports/:campaignId/upload',auth,permit('ADMIN'),upload.single('file'),async(req,res)=>{ if(!req.file) return res.status(400).json({message:'Arquivo obrigatório'}); const rows=await rowsFrom(req.file); let totalImported=0,duplicates=0,invalid=0,blocked=0; const seen=new Set<string>(); for(const row of rows as any[]){const phone=normalizeBrazilPhone(String(row.telefone??'')); if(!isValidBrazilPhone(phone)){invalid++; continue} if(seen.has(phone)){duplicates++; continue} seen.add(phone); if(await prisma.doNotCall.findUnique({where:{phoneNormalized:phone}})){blocked++; continue} try{await prisma.lead.create({data:{campaignId:req.params.campaignId,name:String(row.nome||'Sem nome'),phoneOriginal:String(row.telefone||''),phoneNormalized:phone,cpf:row.cpf?String(row.cpf):undefined,email:row.email?String(row.email):undefined,course:row.curso?String(row.curso):undefined,origin:row.origem?String(row.origem):undefined,notes:row.observacao?String(row.observacao):undefined,status:'EM_FILA'}}); totalImported++;}catch{duplicates++;}} const log=await prisma.importLog.create({data:{campaignId:req.params.campaignId,fileName:req.file.originalname,totalRead:rows.length,totalImported,duplicates,invalid,blocked,createdById:req.user!.id}}); await audit(req.user!.id,'IMPORT_CREATED','ImportLog',log.id,{totalImported,totalRead:rows.length,invalid}); res.json({...log,totalImported,duplicates,invalid,blocked,totalRead:rows.length})});
r.get('/imports',auth,async(_,res)=>res.json(await prisma.importLog.findMany({include:{campaign:true},orderBy:{createdAt:'desc'}})));
r.get('/leads',auth,async(req,res)=>{const q=req.query as any; res.json(await prisma.lead.findMany({where:{campaignId:q.campaignId,status:q.status,operatorId:q.operatorId,phoneNormalized:q.telefone?{contains:q.telefone}:undefined,name:q.nome?{contains:q.nome,mode:'insensitive'}:undefined,origin:q.origem?{contains:q.origem,mode:'insensitive'}:undefined},include:{campaign:true,operator:true},orderBy:{createdAt:'desc'},take:200}))});
r.get('/leads/:id',auth,async(req,res)=>res.json(await prisma.lead.findUnique({where:{id:req.params.id},include:{calls:true,campaign:true,operator:true}})));
r.patch('/leads/:id',auth,async(req,res)=>res.json(await prisma.lead.update({where:{id:req.params.id},data:req.body})));
r.post('/leads/:id/assign',auth,permit('ADMIN','SUPERVISOR'),async(req,res)=>res.json(await prisma.lead.update({where:{id:req.params.id},data:{operatorId:req.body.operatorId,status:'EM_FILA'}})));
r.post('/leads/:id/do-not-call',auth,async(req,res)=>{const l=await prisma.lead.update({where:{id:req.params.id},data:{doNotCall:true,status:'NAO_LIGAR_NOVAMENTE'}}); await prisma.doNotCall.upsert({where:{phoneNormalized:l.phoneNormalized},create:{phoneNormalized:l.phoneNormalized,reason:req.body.reason,blockedById:req.user!.id},update:{reason:req.body.reason,blockedById:req.user!.id}}); await audit(req.user!.id,'LEAD_BLOCKED','Lead',l.id); res.json(l)});
r.post('/calls/start',auth,async(req,res)=>{const lead=await prisma.lead.findUnique({where:{id:req.body.leadId},include:{campaign:true}}); const op=await prisma.user.findUnique({where:{id:req.user!.id}}); if(!lead||lead.doNotCall) return res.status(400).json({message:'Lead inexistente ou bloqueado para ligação'}); try{const out=await getVoipService().originateCall(op?.extension||req.body.operatorExtension||'',lead.phoneNormalized); const c=await prisma.callAttempt.create({data:{leadId:lead.id,campaignId:lead.campaignId,operatorId:req.user!.id,provider:process.env.VOIP_PROVIDER||'mock',providerCallId:out.providerCallId,status:'STARTED',startedAt:new Date()}}); await prisma.lead.update({where:{id:lead.id},data:{status:'LIGANDO',lastAttemptAt:new Date(),attemptsCount:{increment:1}}}); await audit(req.user!.id,'CALL_STARTED','CallAttempt',c.id); res.json(c)}catch(e:any){res.status(400).json({message:e.message})}});
r.post('/calls/:id/finish',auth,async(req,res)=>{const b=finishCallSchema.parse(req.body); const c=await prisma.callAttempt.update({where:{id:req.params.id},data:{status:'COMPLETED',endedAt:new Date(),durationSeconds:b.durationSeconds,finalDisposition:b.finalDisposition,notes:b.notes}}); await prisma.lead.update({where:{id:c.leadId},data:{status:b.finalDisposition,notes:b.notes,callbackAt:b.callbackAt?new Date(b.callbackAt):undefined,doNotCall:b.doNotCall||b.finalDisposition==='NAO_LIGAR_NOVAMENTE'}}); if(b.doNotCall||b.finalDisposition==='NAO_LIGAR_NOVAMENTE') await prisma.doNotCall.upsert({where:{phoneNormalized:(await prisma.lead.findUniqueOrThrow({where:{id:c.leadId}})).phoneNormalized},create:{phoneNormalized:(await prisma.lead.findUniqueOrThrow({where:{id:c.leadId}})).phoneNormalized,blockedById:req.user!.id},update:{blockedById:req.user!.id}}); res.json(c)});
r.get('/calls',auth,async(_,res)=>res.json(await prisma.callAttempt.findMany({include:{lead:true,campaign:true,operator:true},orderBy:{createdAt:'desc'},take:200})));
r.get('/calls/:id',auth,async(req,res)=>res.json(await prisma.callAttempt.findUnique({where:{id:req.params.id},include:{lead:true,campaign:true,operator:true}})));
r.get('/dashboard/summary',auth,async(_,res)=>{const today=new Date();today.setHours(0,0,0,0); const [total,newLeads,callsToday,blocked]=await Promise.all([prisma.lead.count(),prisma.lead.count({where:{status:'NOVO'}}),prisma.callAttempt.count({where:{createdAt:{gte:today}}}),prisma.lead.count({where:{doNotCall:true}})]); const atendidos=await prisma.lead.count({where:{status:'ATENDIDO'}}), interessados=await prisma.lead.count({where:{status:'INTERESSADO'}}), matriculas=await prisma.lead.count({where:{status:'MATRICULADO'}}), nao=await prisma.lead.count({where:{status:'NAO_ATENDEU'}}); res.json({total,newLeads,callsToday,atendidos,naoAtenderam:nao,interessados,matriculas,blocked,taxaAtendimento:callsToday?atendidos/callsToday:0,taxaConversao:total?matriculas/total:0})});
r.get('/dashboard/charts',auth,async(_,res)=>res.json({statusPorCampanha:await prisma.lead.groupBy({by:['campaignId','status'],_count:true}),chamadasPorOperador:await prisma.callAttempt.groupBy({by:['operatorId'],_count:true}),resultadoChamadas:await prisma.callAttempt.groupBy({by:['finalDisposition'],_count:true})}));
r.get('/reports/calls',auth,async(_,res)=>res.json(await prisma.callAttempt.findMany({include:{campaign:true,operator:true,lead:true}})));
r.get('/reports/calls/export',auth,async(req,res)=>{const data=await prisma.callAttempt.findMany({include:{campaign:true,operator:true,lead:true}}); await audit(req.user!.id,'REPORT_EXPORTED','CallAttempt'); res.type('text/csv').send('campanha,operador,nome,telefone,status_lead,status_chamada,ultima_tentativa,tentativas,observacao,data_retorno\n'+data.map(d=>[d.campaign.name,d.operator.name,d.lead.name,d.lead.phoneNormalized,d.lead.status,d.status,d.lead.lastAttemptAt?.toISOString()||'',d.lead.attemptsCount,d.notes||'',d.lead.callbackAt?.toISOString()||''].join(',')).join('\n'))});
r.get('/voip/config',auth,permit('ADMIN'),async(_,res)=>res.json({provider:process.env.VOIP_PROVIDER||'mock',asteriskHost:process.env.ASTERISK_HOST,asteriskPort:process.env.ASTERISK_PORT,asteriskContext:process.env.ASTERISK_CONTEXT,asteriskTrunk:process.env.ASTERISK_TRUNK,operatorPrefix:process.env.ASTERISK_OPERATOR_PREFIX}));
r.patch('/voip/config',auth,permit('ADMIN'),async(req,res)=>res.json(await prisma.voipConfig.create({data:req.body})));
r.post('/voip/test',auth,permit('ADMIN'),async(req,res)=>res.json(await getVoipService().originateCall(req.body.operatorExtension||'1000',req.body.destinationNumber||'11999999999')));
r.get('/do-not-call',auth,async(_,res)=>res.json(await prisma.doNotCall.findMany({orderBy:{blockedAt:'desc'}})));
export default r;